#!/bin/bash
# Program:
#       This program shows "Hello World!" in your screen.
# History:
# 2005/08/23    VBird   First release

[ $1 == 'system_get_disk_volume_status' ] && echo -e "0,1"
[ $1 == 'service_get_smart_disk_list' ] && echo -e "1;0,sda,ST3500414CS;Disk1;ST350041;ST3500414CS;-;-" && echo -e "2;1,sdb,6QM0Z8QP;Disk2;Seagate Barracuda 7200.11;ST3500820AS;-;PASSED [1970/01/01 08:34:09]" && echo -e "2"
[ $1 == 'service_get_smart_test_list' ] && echo -e "0;0"
[ $1 == 'service_set_smart_test_start ' ] && echo -e "1"
[ $1 == 'service_set_smart_schedule' ] && echo -e "3;short;;00;00;1;01,00:00,,,short test" && echo -e "2;short;;02;04;5;01,02:04,Fri,,short test" && echo -e "1;short;;07;04;1;13,07:04,,13th,short test"
[ $1 == 'service_get_smart_schedule_list' ] && echo -e "S.M.A.R.T - Quick;Disk2;13 07:04"
[ $1 == 'service_get_smart_test_status' ] && echo -e "4:sdb,short"
[ $1 == 'system_powermgr_info' ] && echo -e "1,3,10;1,15,3;0,0,1;0,0,0;1,0,0;0,0,3;0,2,0;1;30;1" && echo -e "0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;0,0,0;1;1;1;50"
[ $1 == 'system_hdd_hibernation_setting' ] && echo -e "1"
[ $1 == 'system_power_recovery_setting' ] && echo -e "0"
[ $1 == 'system_fan_control_setting' ] && echo -e "0"
[ $1 == 'system_power_onoff_schedule' ] && echo -e "0"
[ $1 == 'service_get_email_info' ] && echo -e "1;;;;;;25;1"
[ $1 == 'service_get_event_info' ] && echo -e "1;1;1;1;1;1;1;1;1;1;1;1;1;3:0:0:*:0;3:0:0:*:0;1;0;1;1;1"
[ $1 == 'service_get_send_email_test_result' ] && echo -e "1"
[ $1 == 'service_get_usb_storage_info' ] && echo -e "1;JetFlash;Transcend 8GB;8.07;sdc;8.03GB;USBDisk1_c1,3.4G,7.0M,ext4#USBDisk1_c2,3.0G,4.0K,vfat#USBDisk1_c3,1.0G,5.6M,ntfs"
