#!/bin/bash
# Program:
#       This program shows "Hello World!" in your screen.
# History:
# 2005/08/23    VBird   First release

echo -e "#response value"
echo -e error
echo -e 1429755496
echo -e 1429756096
echo -e +8

