#!/bin/bash
# Program:
#       This program shows "Hello World!" in your screen.
# History:
# 2005/08/23    VBird   First release

[ $1 == 'save' ] && echo -e "./faked_api/backupconfig.tar"
[ $1 == 'load' ] && echo -e "0"
