#ifndef FILESUFFIXDESCRIPTION_H
#define FILESUFFIXDESCRIPTION_H

const char SUFFIX_DESCRIPTION_TABLE[][2][255] = {

    { "3gp", 	"3GPP File" },
    { "aiff",	"AIFF Audio File" },
    { "aac", 	"AAC Audio File" },
    { "amr",	"AMR Audio File" },
    { "ape",	"APE Audio File" },
    { "au",		"AU Audio File" },
    { "flac",	"FLAC Audio File" },
    { "m3u",	"M3U Media Playlist" },
    { "midi",	"MIDI Sound File" },
    { "m4a",	"MPEG-4 Audio File" },
    { "m4p",	"M4P Audio File" },
    { "m4r",	"M4R Audio File" },
    { "mp3",	"MP3 Audio File" },
    { "ogg",	"Ogg Vorbis Audio File" },
    { "oga",	"Ogg Vorbis Audio File" },
    { "r1m",	"RealOne Audio File" },
    { "ra",     "RealMedia Audio File" },
    { "wav",	"WAVE Audio File" },
    { "wma",	"Windows Media Audio File" },
    { "gho",	"Ghost Image File" },
    { "gzip",	"GZIP TAR Archive" },
    { "bzip2",	"BZIP2 TAR Archive" },
    { "tar",	"LZMA TAR Archive" },
    { "lzma",	"LZMA TAR Archive" },
    { "7z",     "7-Zip Archive" },
    { "a",      "Archive File" },
    { "arj",	"ARJ Archive" },
    { "bzip",	"BZIP Archive" },
    { "bzip2",	"BZip2 Archive" },
    { "deb",	"Debian Software Package" },
    { "pkg",	"Mac OS X Installer Package" },
    { "rar", 	"RAR Archive" },
    { "r0",     "RAR Archive" },
    { "rpm",	"Redhat Software Package" },
    { "tbz2",	"BZIP2 TAR Archive" },
    { "tlzma",	"LZMA TAR Archive" },
    { "zip",	"ZIP Archive" },
    { "bin",	"Binary File" },
    { "dat",	"Data File" },
    { "db",     "Database File" },
    { "odf",	"Open Document File" },
    { "odp",	"Open Document Presentation" },
    { "ots",	"Open Document Spreadsheet Template" },
    { "pot",	"PowerPoint Template" },
    { "potx",	"PowerPoint Template" },
    { "pps",	"PowerPoint Slide Show" },
    { "ppsx",	"PowerPoint Slide Show" },
    { "ppt",	"PowerPoint Presentation" },
    { "pptx",	"PowerPoint Presentation" },
    { "sql",	"SQL Data File" },
    { "sqlite",	"SQLite Database File" },
    { "udeb",	"Debian Package File" },
    { "xls",	"Excel Spreadsheet" },
    { "xlsx",	"Excel Spreadsheet" },
    { "xsl",	"XML Stylesheet" },
    { "xslt",	"XSL File" },
    { "cue",	"CUE File" },
    { "dmg",	"Mac OS X Disk Image" },
    { "ghs",	"Ghost Disk Image" },
    { "iso",	"CD/DVD Disk Image" },
    { "md5",	"MD5 Checksum File" },
    { "mdf",	"CD/DVD Virtual Image" },
    { "nrg",	"Nero CD/DVD Image" },
    { "vcd",	"Virtual CD Image" },
    { "vmdk",	"VMware Disk Image" },
    { "bmp",	"Bitmap Image File" },
    { "gif",	"GIF Image" },
    { "ico",	"Icon Image" },
    { "icon",	"Icon Image" },
    { "j2k",	"JPEG 2000 Image" },
    { "jpf",	"JPEG 2000 Image" },
    { "jpg2",	"JPEG 2000 Image" },
    { "jiff",	"JPEG Image" },
    { "jpg",	"JPEG Image" },
    { "pdf",	"PDF Document" },
    { "png",	"PNG Image" },
    { "ps",     "PostScript File" },
    { "psb",	"Photoshop Image Document" },
    { "psd",	"Photoshop Image Document" },
    { "webp",	"WebP Image" },
    { "1st",	"Readme Text" },
    { "abw",	"AbiWord Document" },
    { "ans",	"ANSI Text File" },
    { "asc",	"ASCII Text File" },
    { "ascii",	"ASCII Text File" },
    { "doc",	"Word Document" },
    { "docx",	"Word Document" },
    { "dvi",	"TeX Document" },
    { "email",	"Email Message" },
    { "emlx",	"Email Message" },
    { "epub",	"eBook File" },
    { "faq",	"FAQ Document" },
    { "fb2",	"FictionBook 2.0 File" },
    { "latex",	"LaTeX Document" },
    { "log",	"Log File" },
    { "lst",	"List File" },
    { "mbox",	"Mailbox File" },
    { "me",     "Readme File" },
    { "msg",	"Email Message" },
    { "odt",	"OpenOffice Document" },
    { "opf",	"Open eBook File" },
    { "opml",	"OPML File" },
    { "readme",	"Readme Text" },
    { "rtf",	"Rich Text Format File" },
    { "rtx",	"Rich Text Document" },
    { "srt",	"Subtitle File" },
    { "ssa",	"Subtitle File" },
    { "sub",	"Subtitle File" },
    { "tex",	"LaTeX Source" },
    { "text",	"ASCII Text" },
    { "txt",	"Text File" },
    { "3g2",	"3GPP2 File" },
    { "3gp",	"3GPP File" },
    { "asd",	"ASD File" },
    { "asf",	"ASF File" },
    { "asx",	"ASX Video File" },
    { "avi",	"AVI Video File" },
    { "bik",	"BIK Video File" },
    { "divx",	"DivX Movie File" },
    { "dv",     "Digital Video File" },
    { "dvr",	"DVR File" },
    { "dvx",	"Divx Video File" },
    { "evo",	"HD DVD Video File" },
    { "f4v",	"MP4 Video File" },
    { "flv",	"Flash Video File" },
    { "gts",	"GTS File" },
    { "gvi",	"GVI Video File" },
    { "gvp",	"Google Video Pointer" },
    { "ifo",	"DVD Info File" },
    { "m2v",	"M2V Video Stream File" },
    { "m4e",	"MPEG-4 Video File" },
    { "m4u",	"MPEG-4 Playlist" },
    { "m4v",	"M4V Video File" },
    { "mj2",	"Motion JPEG 2000 Video" },
    { "mgp",	"MJPEG Video File" },
    { "mkv",	"MKV Video Stream" },
    { "mnv",	"MNV Movie File" },
    { "mod",	"MOD Video File" },
    { "mov",	"MOV Movie File" },
    { "mp4",	"MPEG-4 Video File" },
    { "mp4v",	"MPEG-4 Video File" },
    { "mpeg",	"MPEG Movie" },
    { "mpg",	"MPEG Video File" },
    { "mpg2",	"MPEG-2 Video File" },
    { "mqv",	"MQV Movie File" },
    { "mts",	"MTS Video File" },
    { "mtv",	"MTV Video File" },
    { "nsv",	"NSV Video File" },
    { "ogv",	"Ogg Vorbis Video" },
    { "ogx",	"OGG Vorbis Media File" },
    { "qt",     "QuickTime Video" },
    { "qtl",	"QuickTime Movie" },
    { "rm",     "RealMedia File" },
    { "rms",	"Secure RealMedia File" },
    { "rmvb",	"RealVideo File" },
    { "rv",     "RealVideo Video" },
    { "svi",	"SVI Video" },
    { "swf",	"SWF Flash File" },
    { "thm",	"Video Thumbnail" },
    { "tivo",	"TiVo Video File" },
    { "ts",     "HDTV Stream File" },
    { "vob",	"DVD Video Object File" },
    { "vp6",	"VP6 Video File" },
    { "vp7",	"VP7 Video File" },
    { "vp8",	"VP8 Video File" },
    { "wmv",	"WMV Media File" },
    { "xfl",	"Flash Movie Archive" },
    { "c",      "C Source File" },
    { "cc",     "C++ Source File" },
    { "cpp",	"C++ Source File" },
    { "cxx",	"C++ Source File" },
    { "cp",     "XCode C++ Source File" },
    { "cs",     "C# .NET Class File" },
    { "csproj",	"Visual Studio C# Project File" },
    { "f77",	"Fortran 77 Source File" },
    { "fpp",	"Fortran 77 Source File" },
    { "gmo",	"GNU Machine Object File" },
    { "h",      "C/C++ Header File" },
    { "has",	"Haskell Script" },
    { "inc",	"Include File" },
    { "jad",	"Java File" },
    { "java",	"Java Source File" },
    { "json",	"JSON File" },
    { "lua",	"Lua Source File" },
    { "mak",	"Makefile" },
    { "mk",     "Makefile" },
    { "mkg",	"Makefile" },
    { "ms",     "MaxScript File" },
    { "mse",	"Encrypted MaxScript File" },
    { "omo",	"OMake Object File" },
    { "p",      "Pascal Source File" },
    { "ph",     "Perl Header File" },
    { "pl",     "Perl Script" },
    { "py",     "Python Script" },
    { "pyd",	"Python Dynamic Module" },
    { "rb",     "Ruby Script" },
    { "sh",     "Shell Script" },
    { "tk",     "Tk Script" },
    { "tcl",	"TCL Script" },
    { "vbx",	"Visual Basic File" },
    { "bat",	"Batch File" },
    { "cgi",	"CGI File" },
    { "cod",	"COD Executable File" },
    { "com",	"Command File" },
    { "dex",	"Android Executable File" },
    { "elf",	"ELF File" },
    { "exe",	"Executable File" },
    { "ipa",	"iPod/iPhone App File" },
    { "jar",	"Java Archive File" },
    { "vb",     "VBScript File" },
    { "vbe",	"VBScript File" },
    { "vbs",	"VBScript File" },
    { "vbscript",	"VBScript File" },
    { "ws",     "Windows Script" },
    { "xbe",	"Xbox Executable File" },
    { "xex",	"Xbox 360 Executable File" },
    { "acfm",	"ACFM Font File" },
    { "amfm",	"AMFM Font File" },
    { "dfont",	"DFont File" },
    { "fnt",	"Font File" },
    { "fon",	"Font File" },
    { "otf",	"OpenType Format Font" },
    { "ttc",	"TTC Font File" },
    { "ttf",	"TTF Font File" },
    { "ipg",	"iPod Game File" },
    { "map",	"Map File" },
    { "nds",	"Nintendo Rom File" },
    { "nes",	"Nintendo Rom File" },
    { "hm3",	"Help & Manual 3 File" },
    { "hmX",	"Help & Manual 4 File" },
    { "msi",	"Windows Installer Package" },
    { "msu",	"Windows Update Package" },
    { "nth",	"Nokia Theme File" },
    { "ods",	"Outlook Express File" },
    { "pls",	"PlayList File" },
    { "skin",	"Skin File" },
    { "torrent",	"BitTorrent File" },
    { "cfg",	"Configuration File" },
    { "ini",	"INI File" },
    { "asp",	"ASP File" },
    { "atom",	"Atom File" },
    { "chm",	"Compiled HTML Help Files" },
    { "css",	"CSS Files" },
    { "dhtml",	"Dynamic HTML File" },
    { "htm",	"HTML File" },
    { "html",	"HTML File" },
    { "htmls",	"HTMLS Files" },
    { "js",     "JavaScript Source File" },
    { "jsp",	"JSP Files" },
    { "php",	"PHP Script" },
    { "php3",	"PHP 3 Script" },
    { "rss",	"RSS File" },
    { "url",	"Internet Shortcut" },
    { "xhtml",	"XHTML File"  },

};

#endif // FILESUFFIXDESCRIPTION_H
