#!/bin/bash
# Program:
#       This program shows "Hello World!" in your screen.
# History:
# 2005/08/23    VBird   First release

echo -e "Jun  9 18:52:11 DNS-320 INFO: Modify Default Gateway : LAN [192.168.100.11]."
echo -e "Jun  9 18:52:33 DNS-320 INFO: Modify LAN [X] IP:[192.168.100.11]."
echo -e "Jun  9 19:02:19 DNS-320 INFO: Modify LAN [X] IP:[192.168.100.11]."
echo -e "Jun  9 19:17:35 DNS-320 WARNING: [192.168.100.1]: [user] Login FAIL."
echo -e "Jun  9 19:18:05 DNS-320 ERROR: [samba] settings failed0."
echo -e "Jun  9 19:19:05 DNS-320 ERROR: [samba] settings failed1."
echo -e "Jun  9 19:20:05 DNS-320 ERROR: [samba] settings failed2."
echo -e "Jun  9 19:21:05 DNS-320 ERROR: [samba] settings failed3."
echo -e "Jun  9 19:22:05 DNS-320 ERROR: [samba] settings failed4."
echo -e "Jun  9 19:23:05 DNS-320 ERROR: [samba] settings failed5."
echo -e "Jun  9 19:24:05 DNS-320 ERROR: [samba] settings failed6."
echo -e "Jun  9 19:25:05 DNS-320 ERROR: [samba] settings failed7."

