#!/bin/bash
# Program:
#       This program shows "Hello World!" in your screen.
# History:
# 2005/08/23	VBird	First release
[ $1 == 'quotainfo' ] && echo -e "1;2814038;5;2;0;Volume_1"
[ $1 == 'remoteinfo' ] && echo -e "Volume_1:/mnt/HD/HD_a2;Volume_2:/mnt/HD/HD_b2"
[ $1 == 'userlist' ] && echo -e "user1;0;Unlimited;0;Unlimited;-;-;-;-" && echo -e "user2;0;100;0;Unlimited;-;-;-;-"
[ $1 == 'grouplist' ] && echo -e "group1;0;Unlimited;0;Unlimited;-;-;-;-" && echo -e "group2;0;100;0;Unlimited;-;-;-;-"
[ $1 == 'usersize' ] && echo -e "2047056"
[ $1 == 'groupsize' ] && echo -e "10240"
[ $1 == 'userset' ] && echo -e "1"
[ $1 == 'groupset' ] && echo -e "1"
[ $1 == 'enable' ] && echo -e "1"
[ $1 == 'get_group_quota_minsize' ] && echo -e "102400:0:0:0"
[ $1 == 'get_user_quota_maxsize' ] && echo -e "2047056"
